<a href="https://colab.research.google.com/github/geovanemelo/data-science/blob/main/An%C3%A1lise_exploratoria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Análise exploratória

é dificil delimitar esse processo. Envolve toda etapa de aquisição e importação dos dados.

Existém varia técnicas e dependentes de cada problema e dataset. Nesse nootebook iremos ver alguns exemplos

Começamos importando um dataset de ocorrências da aviação civil do Brasil

In [ ]:
DATA_PATH = "https://raw.githubusercontent.com/carlosfab/dsnp2/master/datasets/ocorrencias_aviacao.csv"

# importando os pacotes
import pandas as pd

# importando o arquivo csv
df = pd.read_csv(DATA_PATH, index_col="codigo_ocorrencia")

# ver as primeiras entradas
df.head()

                  ocorrencia_classificacao  ... ocorrencia_dia_extracao
codigo_ocorrencia                           ...
201305055424986                   ACIDENTE  ...              2018-08-28
201605160250139            INCIDENTE GRAVE  ...              2018-08-28
201805021421302                  INCIDENTE  ...              2018-08-28
201311259977425            INCIDENTE GRAVE  ...              2018-08-28
201103187273112                  INCIDENTE  ...              2018-08-28

[5 rows x 21 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5208 entries, 201305055424986 to 201309012098180
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ocorrencia_classificacao        5208 non-null   object
 1   ocorrencia_tipo                 5208 non-null   object
 2   ocorrencia_tipo_categoria       5208 non-null   object
 3   ocorrencia_tipo_icao            5208 non-null   object
 4   ocorrencia_latitude             5208 non-null   float64
 5   ocorrencia_longitude            5208 non-null   float64
 6   ocorrencia_cidade               5208 non-null   object
 7   ocorrencia_uf                   5208 non-null   object
 8   ocorrencia_pais                 5208 non-null   object
 9   ocorrencia_aerodromo            5208 non-null   object
 10  ocorrencia_dia                  5208 non-null   object
 11  ocorrencia_horario              5208 non-null   object
 12  investigacao_aeronave_liberada  1110 non-null   object
 13  investigacao_status             5208 non-null   object
 14  divulgacao_relatorio_numero     5208 non-null   object
 15  divulgacao_relatorio_publicado  5208 non-null   object
 16  divulgacao_dia_publicacao       1261 non-null   object
 17  total_recomendacoes             5208 non-null   int64
 18  total_aeronaves_envolvidas      5208 non-null   int64
 19  ocorrencia_saida_pista          5208 non-null   object
 20  ocorrencia_dia_extracao         5208 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 895.1+ KB

#Valores únicos

P/ ver quais são todos valores unico de uma coluna, usamos o `unique()`

In [ ]:
df.ocorrencia_classificacao.unique()

array(['ACIDENTE', 'INCIDENTE GRAVE', 'INCIDENTE'], dtype=object)

In [ ]:
df.ocorrencia_tipo.unique()

array(['FALHA DO MOTOR EM VOO',
       'COLISÃO COM OBSTÁCULO DURANTE A DECOLAGEM E POUSO', 'AERÓDROMO',
       'POUSO SEM TREM', 'OUTROS', 'PERDA DE CONTROLE NO SOLO',
       'POUSO LONGO', 'TRÁFEGO AÉREO', 'PERDA DE CONTROLE EM VOO',
       'COM TREM DE POUSO', 'INDETERMINADO', 'ESTOURO DE PNEU',
       'VOO CONTROLADO CONTRA O TERRENO', 'EXCURSÃO DE PISTA',
       'POUSO BRUSCO', 'CAUSADO POR FENÔMENO METEOROLÓGICO EM VOO',
       'INCURSÃO EM PISTA', 'VAZAMENTO DE OUTROS FLUIDOS', 'COM ROTOR',
       'FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE ',
       'PERDA DE COMPONENTE EM VOO', 'SOPRO DE REATOR',
       'COM PARA-BRISAS / JANELA / PORTA', 'COM LANÇAMENTO DE CARGA',
       'POUSO ANTES DA PISTA', 'F.O.D.', 'PROBLEMAS FISIOLÓGICOS',
       'DESCOMPRESSÃO NÃO INTENCIONAL / EXPLOSIVA',
       'COLISÃO DE VEÍCULO COM AERONAVE', 'FOGO NO SOLO', 'FOGO EM VOO',
       'CAUSADO POR FENÔMENO METEOROLÓGICO NO SOLO', 'COM PESSOAL EM VOO',
       'COLISÃO DE AERONAVES EM VOO', 'FUMAÇA NA CABINE',
       'COLISÃO COM OBSTÁCULOS NO SOLO', 'PERDA DE COMPONENTE NO SOLO',
       'SOPRO DE ROTOR', 'FALHA DO MOTOR NO SOLO', 'SUPERAQUECIMENTO',
       'COM COMANDOS DE VOO', 'FALHA ESTRUTURAL',
       'POUSO EM LOCAL NÃO PREVISTO', 'DESORIENTAÇÃO ESPACIAL',
       'VAZAMENTO DE COMBUSTÍVEL', 'PANE SECA',
       'COLISÃO COM AERONAVE NO SOLO', 'CORTE INVOLUNTÁRIO DO MOTOR',
       'TURBULÊNCIA', 'OPERAÇÃO A BAIXA ALTITUDE', 'COM HÉLICE',
       'COM LANÇAMENTO DE PESSOAS', 'COLISÃO EM VOO COM OBJETO REBOCADO',
       'AERONAVE ATINGIDA POR OBJETO',
       'FALHA OU MAU FUNCIONAMENTO DO MOTOR',
       'CONTATO ANORMAL COM A PISTA ', 'CORTANTE DE VENTO / TEMPESTADE',
       'OPERAÇÕES NO SOLO', 'CAUSADO POR RICOCHETE',
       'RELACIONADO COM SECURITY', 'PERDA DA CONSCIÊNCIA',
       'ALARME FALSO DE FOGO OU DE SUPERAQUECIMENTO', 'MANOBRA ABRUPTA'],
      dtype=object)

#Porcentagem dos valores em cada coluna

In [ ]:
df.ocorrencia_tipo.value_counts(1)
#ou
df.ocorrencia_tipo.value_counts() / df.shape[0]

FALHA DO MOTOR EM VOO                                  0.130952
ESTOURO DE PNEU                                        0.115975
FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPONENTE     0.110215
PERDA DE CONTROLE NO SOLO                              0.094470
OUTROS                                                 0.067204
                                                         ...
RELACIONADO COM SECURITY                               0.000192
PERDA DA CONSCIÊNCIA                                   0.000192
ALARME FALSO DE FOGO OU DE SUPERAQUECIMENTO            0.000192
CORTANTE DE VENTO / TEMPESTADE                         0.000192
MANOBRA ABRUPTA                                        0.000192
Name: ocorrencia_tipo, Length: 63, dtype: float64

#Filtrando os valores
Existem dois metodos para essa tecnica, usadas de forma diferente.

##loc

Para usar esta opção, você deve entender que o mesmo funciona da seguinte maneira:

`loc [<linhas>,<colunas>]`

Este método pode ser usado em duas situações:

Selecionar linhas por labels/index
Selecionar linhas baseado em um array booleano
Vou dar um exemplo da primeira situação em que podemos usar loc. Suponha que eu precise extrair a latitude e longitude do local onde aconteceu a ocorrência de número 200808073991179:

In [ ]:
df.loc[200808073991179,['ocorrencia_latitude', 'ocorrencia_longitude']]

ocorrencia_latitude     -9.1194
ocorrencia_longitude   -68.5978
Name: 200808073991179, dtype: object

In [ ]:

# ver apenas as 5 primeiras entradas da situação
df.loc[df["ocorrencia_tipo"] == "FALHA DO MOTOR EM VOO"].head()

                  ocorrencia_classificacao  ... ocorrencia_dia_extracao
codigo_ocorrencia                           ...
201305055424986                   ACIDENTE  ...              2018-08-28
201211159478138                   ACIDENTE  ...              2018-08-28
200811167138358                   ACIDENTE  ...              2018-08-28
201111224132085                   ACIDENTE  ...              2018-08-28
201509183338691                   ACIDENTE  ...              2018-08-28

[5 rows x 21 columns]

##iloc
O uso do `iloc` é mais simples, pois a gente passa seleciona linhas e colunas usando números, na mesma ordem em que aparecem no *DataFrame*:

`loc[<numero_da_linha>, <numero_da_coluna>]`

Eu consigo selecionar um *range* de interesse. Por exemplo, para selecionar as 3 primeiras entradas e as 4 primeiras colunas, eu faria da seguinte maneira:

In [ ]:
df.iloc[:3,4:]

                   ocorrencia_latitude  ...  ocorrencia_dia_extracao
codigo_ocorrencia                       ...
201305055424986                -9.9085  ...               2018-08-28
201605160250139               -11.2644  ...               2018-08-28
201805021421302               -11.4956  ...               2018-08-28

[3 rows x 17 columns]

In [ ]:
#uf's que apresentam aciddentes
df.loc[df.ocorrencia_uf == '***']

                  ocorrencia_classificacao  ... ocorrencia_dia_extracao
codigo_ocorrencia                           ...
201503065919795                   ACIDENTE  ...              2018-08-28
200803063018556                  INCIDENTE  ...              2018-08-28
201309012098180                   ACIDENTE  ...              2018-08-28

[3 rows x 21 columns]